// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BleEnroll(arg1) {
  return window['go']['desktop']['App']['BleEnroll'](arg1);
}

export function BleSupported() {
  return window['go']['desktop']['App']['BleSupported']();
}

export function Context() {
  return window['go']['desktop']['App']['Context']();
}

export function DeleteC8YCredential(arg1) {
  return window['go']['desktop']['App']['DeleteC8YCredential'](arg1);
}

export function DeleteProfileFile(arg1) {
  return window['go']['desktop']['App']['DeleteProfileFile'](arg1);
}

export function GetRuntimeInfo() {
  return window['go']['desktop']['App']['GetRuntimeInfo']();
}

export function ListC8YCredentials() {
  return window['go']['desktop']['App']['ListC8YCredentials']();
}

export function ListProfileFiles() {
  return window['go']['desktop']['App']['ListProfileFiles']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['desktop']['App']['OnSecondInstanceLaunch'](arg1);
}

export function OpenConfigDirectory() {
  return window['go']['desktop']['App']['OpenConfigDirectory']();
}

export function ReadProfileFile(arg1) {
  return window['go']['desktop']['App']['ReadProfileFile'](arg1);
}

export function RevealSealedProfile(arg1) {
  return window['go']['desktop']['App']['RevealSealedProfile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['desktop']['App']['SaveFile'](arg1, arg2);
}

export function SealProfile(arg1, arg2) {
  return window['go']['desktop']['App']['SealProfile'](arg1, arg2);
}

export function SealProfileForSave(arg1) {
  return window['go']['desktop']['App']['SealProfileForSave'](arg1);
}

export function SetC8YCredential(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['SetC8YCredential'](arg1, arg2, arg3, arg4);
}

export function SetContext(arg1) {
  return window['go']['desktop']['App']['SetContext'](arg1);
}

export function WriteProfileFile(arg1, arg2) {
  return window['go']['desktop']['App']['WriteProfileFile'](arg1, arg2);
}
