// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {context} from '../models';

export function BleEnroll(arg1:number):Promise<desktop.BleEnrollResult>;

export function BleSupported():Promise<boolean>;

export function Context():Promise<context.Context>;

export function GetRuntimeInfo():Promise<desktop.RuntimeInfo>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
