// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BleEnroll(arg1) {
  return window['go']['desktop']['App']['BleEnroll'](arg1);
}

export function BleSupported() {
  return window['go']['desktop']['App']['BleSupported']();
}

export function Context() {
  return window['go']['desktop']['App']['Context']();
}

export function GetRuntimeInfo() {
  return window['go']['desktop']['App']['GetRuntimeInfo']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['desktop']['App']['OnSecondInstanceLaunch'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['desktop']['App']['SaveFile'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['desktop']['App']['SetContext'](arg1);
}
