// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {context} from '../models';
import {options} from '../models';

export function BleEnroll(arg1:number):Promise<desktop.BleEnrollResult>;

export function BleSupported():Promise<boolean>;

export function Context():Promise<context.Context>;

export function DeleteC8YCredential(arg1:string):Promise<void>;

export function GetRuntimeInfo():Promise<desktop.RuntimeInfo>;

export function ListC8YCredentials():Promise<Array<desktop.C8YCredential>>;

export function ListProfileFiles():Promise<Array<string>>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function OpenConfigDirectory():Promise<void>;

export function ReadProfileFile(arg1:string):Promise<string>;

export function RevealSealedProfile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SealProfile(arg1:string,arg2:string):Promise<string>;

export function SealProfileForSave(arg1:string):Promise<string>;

export function SetC8YCredential(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function DeleteProfileFile(arg1:string):Promise<void>;

export function WriteProfileFile(arg1:string,arg2:string):Promise<void>;
