//! Cross-language wire-protocol test vectors.
//!
//! These tests consume JSON fixtures generated by the Go test generators at
//! pkg/protocol/testvectors_gen_test.go and testvectors_p256_gen_test.go. The fixtures are .gitignore'd (they
//! contain deterministic synthetic keys). They are regenerated automatically:
//!
//!   • `go test ./pkg/protocol` — regenerates testdata/vectors/ as a side-effect.
//!   • `cargo build` / `cargo test`  — build.rs runs the Go generator first.
//!
//! Each test validates that the Rust implementation produces byte-identical
//! output to the Go implementation for the same input.

use base64::{engine::general_purpose::STANDARD, Engine as _};
use serde::Deserialize;
use std::path::PathBuf;

fn vectors_dir() -> PathBuf {
    // File is at clients/rust/tests/protocol_vectors.rs
    // testdata/vectors/ is at repo_root/testdata/vectors/
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    PathBuf::from(manifest).join("../../testdata/vectors")
}

fn read_vector_file(name: &str) -> Option<String> {
    let path = vectors_dir().join(name);
    std::fs::read_to_string(&path).ok()
}

// ---- canonical --------------------------------------------------------------

#[derive(Deserialize)]
struct CanonicalCase {
    input: serde_json::Value,
    expected: String, // base64 of canonical bytes
}

#[test]
fn canonical_vectors() {
    let json = match read_vector_file("canonical.json") {
        Some(s) => s,
        None => {
            eprintln!("SKIP: testdata/vectors/canonical.json not found — run the Go generator first");
            return;
        }
    };
    let cases: Vec<CanonicalCase> = serde_json::from_str(&json).expect("parse canonical.json");
    assert!(!cases.is_empty(), "no canonical test cases");

    for (i, c) in cases.iter().enumerate() {
        let expected = STANDARD.decode(&c.expected).expect("decode expected base64");
        let got = ztp_agent::canonical::canonicalize_value(&c.input);
        assert_eq!(
            got, expected,
            "canonical case[{i}]: input={:?}\n  got:  {}\n  want: {}",
            c.input,
            String::from_utf8_lossy(&got),
            String::from_utf8_lossy(&expected)
        );
    }
}

// ---- sign -------------------------------------------------------------------

#[derive(Deserialize)]
struct SignVector {
    priv_key_b64: String,
    pub_key_b64: String,
    canonical_b64: String,   // base64 of canonical bytes
    signature_b64: String,   // base64 of ed25519 signature
}

#[test]
fn sign_vectors() {
    let json = match read_vector_file("sign.json") {
        Some(s) => s,
        None => {
            eprintln!("SKIP: testdata/vectors/sign.json not found");
            return;
        }
    };
    let vectors: Vec<SignVector> = serde_json::from_str(&json).expect("parse sign.json");
    assert!(!vectors.is_empty());

    for (i, v) in vectors.iter().enumerate() {
        let priv_bytes = STANDARD.decode(&v.priv_key_b64).expect("decode priv key");
        let seed: &[u8; 32] = &priv_bytes[..32]
            .try_into()
            .expect("priv key seed must be 32 bytes");
        let signing_key = ed25519_dalek::SigningKey::from_bytes(seed);
        let pub_key = signing_key.verifying_key();

        let expected_pub = STANDARD.decode(&v.pub_key_b64).expect("decode pub key");
        assert_eq!(
            pub_key.as_bytes().as_slice(),
            expected_pub.as_slice(),
            "public key mismatch for vector[{i}]"
        );

        let canon_bytes = STANDARD.decode(&v.canonical_b64).expect("decode canonical");
        let exp_sig = STANDARD.decode(&v.signature_b64).expect("decode sig");

        // 1. Check that we can verify the Go-generated signature
        let exp_sig_arr: [u8; 64] = exp_sig.as_slice().try_into().expect("sig must be 64 bytes");
        let sig = ed25519_dalek::Signature::from_bytes(&exp_sig_arr);
        use ed25519_dalek::Verifier;
        pub_key
            .verify(&canon_bytes, &sig)
            .unwrap_or_else(|e| panic!("vector[{i}] Go signature must verify: {e}"));

        // 2. Check that we produce the same signature (Ed25519 is deterministic)
        use ed25519_dalek::Signer;
        let our_sig = signing_key.sign(&canon_bytes);
        assert_eq!(
            our_sig.to_bytes().as_slice(),
            exp_sig.as_slice(),
            "vector[{i}] signature mismatch: Rust and Go must produce identical Ed25519 signatures"
        );
    }
}

// ---- seal -------------------------------------------------------------------

#[derive(Deserialize)]
struct SealVector {
    device_priv_b64: String,
    server_eph_pub_b64: String,
    nonce_b64: String,
    plaintext_b64: String,
    ciphertext_b64: String,
}

#[derive(Deserialize)]
struct SealVectors {
    encrypted_payload: SealVector,
    sealed_module: SealVector,
}

#[test]
fn seal_vectors() {
    let json = match read_vector_file("seal.json") {
        Some(s) => s,
        None => {
            eprintln!("SKIP: testdata/vectors/seal.json not found");
            return;
        }
    };
    let vectors: SealVectors = serde_json::from_str(&json).expect("parse seal.json");

    for (label, v) in [
        ("encrypted_payload", &vectors.encrypted_payload),
        ("sealed_module", &vectors.sealed_module),
    ] {
        let device_priv: [u8; 32] = STANDARD
            .decode(&v.device_priv_b64)
            .expect("decode device priv")
            .try_into()
            .expect("device priv must be 32 bytes");

        let expected_plaintext = STANDARD.decode(&v.plaintext_b64).expect("decode plaintext");
        let nonce_bytes = STANDARD.decode(&v.nonce_b64).expect("decode nonce");
        let ciphertext_bytes = STANDARD.decode(&v.ciphertext_b64).expect("decode ciphertext");

        // Construct the wire type and decrypt
        let ep = ztp_agent::encrypt::EncryptedPayload {
            alg: "x25519-chacha20poly1305".to_string(),
            server_key: v.server_eph_pub_b64.clone(),
            nonce: v.nonce_b64.clone(),
            ciphertext: v.ciphertext_b64.clone(),
        };
        let got = ztp_agent::encrypt::open_for_device(
            &ztp_agent::encrypt::EphemeralKey::X25519(device_priv),
            &ep,
        )
            .unwrap_or_else(|e| panic!("{label}: open_for_device failed: {e}"));

        assert_eq!(
            got, expected_plaintext,
            "{label}: decrypted plaintext mismatch"
        );
    }
}

// ---- enroll request --------------------------------------------------------

#[derive(Deserialize)]
struct EnrollRequestVector {
    priv_key_b64: String,
    pub_key_b64: String,
    canonical_b64: String,
    signed_envelope: ztp_agent::sign::SignedEnvelope,
}

#[test]
fn enroll_request_vector() {
    let json = match read_vector_file("enroll_request.json") {
        Some(s) => s,
        None => {
            eprintln!("SKIP: testdata/vectors/enroll_request.json not found");
            return;
        }
    };
    let v: EnrollRequestVector =
        serde_json::from_str(&json).expect("parse enroll_request.json");

    let pub_key = ztp_agent::sign::decode_public_key(&v.pub_key_b64).expect("decode pub key");

    // Verify that the Go-generated signed envelope passes Rust's verify()
    let payload_bytes = ztp_agent::sign::verify(&v.signed_envelope, &pub_key)
        .expect("Go-signed envelope must verify in Rust");

    // The returned payload bytes must match the canonical bytes in the vector
    let expected_canon = STANDARD.decode(&v.canonical_b64).expect("decode canonical");
    assert_eq!(
        payload_bytes, expected_canon,
        "verified payload bytes must match canonical_b64"
    );

    // Parse the payload as an EnrollRequest and check a stable field
    let req: serde_json::Value =
        serde_json::from_slice(&payload_bytes).expect("parse enroll request");
    assert_eq!(req["device_id"], "test-device-001");
    assert_eq!(req["protocol_version"], "1");
}

// ---- P-256 suite ----------------------------------------------------------

#[derive(Deserialize)]
struct SignP256Vector {
    pub_key_b64: String,
    canon_b64: String,
    sig_b64: String,
    alg: String,
}

/// Go-generated ECDSA P-256 envelopes must verify in Rust. ECDSA signatures
/// are randomised in Go, so (unlike Ed25519) only verification is pinned.
#[test]
fn sign_p256_vectors() {
    let json = match read_vector_file("sign_p256.json") {
        Some(s) => s,
        None => {
            eprintln!("SKIP: testdata/vectors/sign_p256.json not found");
            return;
        }
    };
    let vectors: Vec<SignP256Vector> = serde_json::from_str(&json).expect("parse sign_p256.json");
    assert!(!vectors.is_empty());

    for (i, v) in vectors.iter().enumerate() {
        let pub_key = ztp_agent::sign::decode_public_key(&v.pub_key_b64).expect("decode pub key");
        assert_eq!(pub_key.suite(), ztp_agent::suite::Suite::P256, "vector[{i}]");
        let env = ztp_agent::sign::SignedEnvelope {
            protocol_version: "1".to_string(),
            key_id: "device".to_string(),
            alg: v.alg.clone(),
            payload: v.canon_b64.clone(),
            signature: v.sig_b64.clone(),
        };
        let payload = ztp_agent::sign::verify(&env, &pub_key)
            .unwrap_or_else(|e| panic!("vector[{i}] Go P-256 signature must verify: {e}"));
        assert_eq!(payload, STANDARD.decode(&v.canon_b64).unwrap());

        // Flipping a payload byte must break the signature.
        let mut tampered = payload.clone();
        tampered[0] ^= 1;
        let bad = ztp_agent::sign::SignedEnvelope { payload: STANDARD.encode(tampered), ..env };
        assert!(ztp_agent::sign::verify(&bad, &pub_key).is_err(), "vector[{i}] tamper");
    }
}

#[derive(Deserialize)]
struct SealP256Vector {
    device_priv_b64: String,
    device_pub_b64: String,
    ephemeral_pub_b64: String,
    nonce_b64: String,
    ciphertext_b64: String,
    plaintext_b64: String,
    format: String,
    alg: String,
}

#[test]
fn seal_p256_vectors() {
    let json = match read_vector_file("seal_p256.json") {
        Some(s) => s,
        None => {
            eprintln!("SKIP: testdata/vectors/seal_p256.json not found");
            return;
        }
    };
    let v: SealP256Vector = serde_json::from_str(&json).expect("parse seal_p256.json");

    let scalar = STANDARD.decode(&v.device_priv_b64).expect("decode device priv");
    let device = ztp_agent::encrypt::EphemeralKey::P256(
        p256::SecretKey::from_slice(&scalar).expect("device priv must be a P-256 scalar"),
    );
    assert_eq!(device.public_b64(), v.device_pub_b64, "device pub derivation");
    let expected = STANDARD.decode(&v.plaintext_b64).unwrap();

    // Per-module sealing.
    let sealed = ztp_agent::encrypt::SealedPayload {
        alg: v.alg.clone(),
        ephemeral_pub: v.ephemeral_pub_b64.clone(),
        nonce: v.nonce_b64.clone(),
        ciphertext: v.ciphertext_b64.clone(),
        format: v.format.clone(),
    };
    let (got, format) = ztp_agent::encrypt::open_sealed_module(&device, &sealed)
        .expect("open Go-sealed P-256 module");
    assert_eq!(got, expected);
    assert_eq!(format, v.format);

    // Whole-bundle encryption shares the same construction.
    let ep = ztp_agent::encrypt::EncryptedPayload {
        alg: v.alg.clone(),
        server_key: v.ephemeral_pub_b64.clone(),
        nonce: v.nonce_b64.clone(),
        ciphertext: v.ciphertext_b64.clone(),
    };
    assert_eq!(ztp_agent::encrypt::open_for_device(&device, &ep).unwrap(), expected);
}

// ---- end of protocol_vectors.rs -------------------------------------------
