// Package sopsage implements the SOPS (Mozilla/getsops) YAML on-disk
// encryption format using age as the only key-management backend.
//
// Why a hand-rolled implementation? Importing github.com/getsops/sops/v3
// transitively pulls in ~340 modules including the full AWS, GCP, Azure
// and Vault SDKs (the upstream library wires every key-management backend
// unconditionally). For a deployment that only needs age recipients, that
// represents tens of megabytes of compiled binary growth and a much larger
// supply-chain attack surface for no value. Implementing the format
// directly costs roughly 600 lines of well-tested code and lets us track
// the SOPS spec at our own pace.
//
// On-disk format reference (also see testdata/ fixtures generated by the
// upstream sops CLI):
//
//   - Each YAML leaf the encryption rules select is rewritten as a
//     printable token of the shape
//     "ENC[AES256_GCM,data:<b64>,iv:<b64-32B>,tag:<b64-16B>,type:<T>]".
//   - "iv" is 32 random bytes (sops uses cipher.NewGCMWithNonceSize(c,32)
//     rather than the standard 12-byte GCM nonce).
//   - The cipher additional-data per leaf is the dotted YAML key path
//     joined with ":", with a trailing ":" (e.g. "nested:password:").
//     Sequence indices are deliberately NOT in the AAD; this matches
//     upstream sops behaviour.
//   - "type" is one of str/int/float/bool/bytes; non-string values are
//     stringified before encryption and re-typed on decrypt.
//   - The data key (32 random bytes) is age-encrypted to each recipient
//     and stored under the top-level "sops:" map as a list of
//     {recipient, enc} entries (enc is PEM-armored age ciphertext).
//   - "sops.mac" is itself an ENC[…] token; the plaintext is a hex-encoded
//     HMAC-SHA512 (key = hex(data key)) over the concatenation of every
//     leaf's stringified plaintext, walked in document order.
//   - The MAC's per-leaf AAD is the lastmodified timestamp (also stored
//     under the sops map). This binds the MAC to the modification time
//     so an attacker can't replay an older sops block.
//
// The package is deliberately scoped to the file-format surface needed
// by ztp-server (decrypt at load time) and ztpctl (seal/edit/set/reveal).
// PGP, KMS, GCP-KMS, Azure Key Vault, Hashicorp Vault, and the SOPS
// key-rotation/audit features are intentionally omitted.
package sopsage
